markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "XuKe"
markdown: rdiscount

author: "XuKe"
atom-baseurl: "https://xuker.github.io"
disqus: "gopherwood"

navigations:
  - title: 存档
    class: fa fa-list-ul
    href: /archive.html
  - title: 标签
    class: fa fa-tags
    href: /tags.html
  - title: 关于
    class: fa fa-user
    href: /about.html


baseurl: /xuker.github.io
