markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "XuKe"
markdown: rdiscount

author: "xuke"
atom-baseurl: "https://xuker.github.io"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://xuker.github.io
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml


baseurl: /xuker.github.io
